title: My GitHub Blog
author: Abinav Bharadwaj
email: abhara2@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  Soon to be a data science blog!

# social links
twitter_username: @Abinav_
github_username:  abinavbharadwaj

show_excerpts: true # set to false to remove excerpts on the homepage

minima jekyll-theme-architect
